services:
  backend:
    build:
      context: ./docker/images/backend/
    networks:
      - dev
    volumes:
      - "./:/var/www/html"
      - "./docker/config/backend/php.ini:/etc/php/8.3/fpm/php.ini"

  webserver:
    image: nginx:latest
    networks:
      - dev
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
      - "./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"

  db:
    image: yobasystems/alpine-mariadb:10.11.6
    container_name: db_raidplanner
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass123
    ports:
      - "3306:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_raidplanner
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: