name: Codeception Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: curl, mbstring, openssl, pdo, pdo_sqlite
          ini-values: memory_limit=-1, date.timezone=UTC
          coverage: xdebug
          tools: composer

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Symfony CLI
        run: |
          wget https://get.symfony.com/cli/installer -O - | bash
          sudo mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Start database
        run: docker-compose -f docker-compose.light.yaml up -d

      - name: Install dependencies and build
        run: yarn dependencies

      - name: Run tests
        run: yarn test
